var GAME_LEVELS = [
  ["  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "  x                                                                            x ",
   "  x                     ooooooooooooo t                                        x ",
   "  x@             x m                          x                                x ",
   "  xxxxxx         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!x ",
   "  xooooxxxx  xxxxxxx          ooooooooooooo              xxxxxxxxxxxxxxxxxxxxxxx ",
   "  xooo                                                                         x ",
   "  x                                                                            x ",
   "  x        x               x         m               x                         x ",
   "  x        m          x    xxxxxxxxxxxxxxxxxxxxxxxxxxx                      tyyx ",
   "  xxxxxxxxxxxxxxxxxxxxx                                    y                 yyx ",
   "  x                                                                            x ",
   "  x                                  t     x                           m       x ",
   "  x              x         m            x  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "  x         0    xxxxxxxxxxxxxxxxxxxxxxxx                                      x ",
   "  xy   xxxxxxxxxx                                                              x ",
   "  x                                                                            x ",
   "  x                                               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "  xxxxxxxx            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                      x ",
   "  xt                                                                           x ",
   "  x                                                                            x ",
   "  x y                 o                                                     ooox ",
   "  xxxxxxxxxxxxxxx   xxxxxxx  xxxxxxxxxxxx                                y  xxxx ",
   "  x!!!!!!!!!xooooooox!!!!!!!!xxxxxxxxxxxxx yy o                         xxxx!!!x ",
   "  x!!!!!!!!xxooooooxx!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxx yyt       x!!!!!!!!x ",
   "  x!!!!!!!xxxoooooxxx!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!x ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "                                                                                 ",
   "                                                                                 ",
   "                                                                                 ",
   "                                                                                 ",
   "                                                                                 "],
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x                                                                                                                                                                x ",
   "x                                                                                                                                                                x ",
   "x@  x                                                                                                                                                            x ",
   " xxx                                                                                                                                                             x ",
   " x    =         x t                                                                                                                                              x ",
   "  xo     =        x           t                  x                          t                                                                                    x ",	
   "   x   =        x  xo        ox                 x       m                                xm                                                               x      x ",	
   "    xo           x               x             x xy    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     x ",
   "     x                                        x   x    x    x!!!!!!xxxx!!xxxx!!!!!x!!!!!xxxx!xxxx!!x!!!!!!x       xv!!!!x!!!!!xx!!!x!!!!xxx!!!!!!x       x x=    x ",
   "      x       x0                   oxx      ox     x   x   x x!!!v!x!!!v!x!!!v!!!x x!!!vx!!!vx!!!v!!!v!!!x x     x     x x!!!xxxxv!!!!vx   xv!!!x x     x  x     x ",
   "       x   x   x o               0  x       x       x  x  x   x    xxxx  xxxx   x   x   xxxx xxxx xxx   x   x   x     x   x  vxx  xxx  x   x   x   x   x   x     x ",	
   "        xo     xxx o            o xxx      x         x x xxxxxxx      x     x  xxxxxxx     x    x xxx  x     x x     xxxxxxx  xx  xxx  x   x  x     x x    x     x ",	
   "         xo     xxxx     o     mxxxx      x           xxx oooo  x  xxxx  xxxx x oooo  x xxxx xxxx xxx x  oo   x t   x  oooo x xxo xxx   xxx  x oooo  x ooo x     x ",
   "          xo     xxxxxxxxxxxxxxxxxx      x             x                                                                           o                             x ",
   "           x!!!!!!xxxxxxxxxxxxxxxx!!!!!!x              x                                                                                                         x ",
   "            x!!!!!!!xxxxxxxxxxxx!!!!!!!x               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",	
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
   ["x                                          xxxxxxxxxxxxxxx                                                      ",
    "x                                          x!!!!!!!!!!!!!x                                                      ",
	"x                                           x!!!!!!!!!!!x                  o                                    ",
	"x                                            x!!!!!!!!!x                                                        ",
	"x                                             x!!!!!!!x                                                         ",
	"x                    o                         x!!!!!x                 t  xx                                    ",
	"x                    x     =         x          x!!!x                 xx                                        ",
	"x                   o                            xvx                                                            ",
	"x                   x   =          x                                          xx                                ",
	"x                              x mo       x         t                                                           ",
	"x       xxxx   xxxxxx          xxxxxxxxxxxxxxxxx    x                 xx                                        ",
	"x             x      !!!!!!                    xo   x                                                           ",
	"x            x      !!!!!!!!                   xx   x                                                           ",
	"x           x                                  x   ox                     o                                     ",
	"x          x                                   x   xx                    xxxx                                   ",
	"x         x                                    x    x              o   y!!!!!!!                                 ",
	"x         x                                    xo   x             xxxxx!!!!!!!!!xxxx                            ",
	"x       xxx                                    xx   x      o   !!!!!!!!!!!!!!!!!!!!!!                           ",
	"x      x  x                                    x           xxxx!!!!!!!!!!!!!!!!!!!!!!xxxx         o             ",
	"x     x                                        x o     mx  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxx                  ",
	"x    x                                         xxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
	"x   x                                                                                                           ",
	"x  x                                                                                                            ",
    "x@x                                                                                                             ",
	"xxx                                                                                                             ",	
    "                                                                                                                ",
	"                                                                                                                "],
	["                                                                                                     ",
	"                                                                                                      ",
	"  @                                                                                                   ",
	"  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	"  x                                                                                                   x",
	"  x   x     x     xxxxxx     x         x     x                             x      x    x          x   x",
	"  x    x   x     x      x    x         x      x                           x      x x   x x        x   x",
	"  x     x x     x        x   x         x       x                         x        x    x  x       x   x",
	"  x      x      x        x   x         x        x           x           x              x   x      x   x",
	"  x      x      x        x   x         x         x         x x         x          x    x    x     x   x",
	"  x      x      x        x   x         x          x       x   x       x           x    x     x    x   x",
	"  x      x      x        x   x         x           x     x     x     x            x    x      x   x   x",
	"  x      x      x        x    x       x             x   x       x   x             x    x       x  x   x",
	"  x      x       x      x      x     x               x x         x x              x    x        x x   x",
	"  x      x        xxxxxx        xxxxx                 x           x               x    x         x    x",
	"  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
];
	if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS; 
